PayAssistantBundle\Entity\Action:
    type: entity
    table: action
    indexes:
        definition_id:
            columns:
                - definition_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        value:
            type: integer
            nullable: false
            options:
                unsigned: false
        status:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        definition:
            targetEntity: Definition
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                definition_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
